Use `@types/simple-oauth2` instead of redoing it
fastify/fastify-oauth2 pull request #225
Opened 2023-08-25 22:02 UTC by voxpelli

Prior to https://github.com/fastify/fastify-oauth2/pull/172 the `Credentials` was typed to a much more slim subset of what `simple-oauth2` currently accepts, but in #172 (which contained #170 that fixed #152) it was extended to pretty much be the full typing of `simple-oauth2`, but without actually referring to `@types/simple-oauth2`.

This PR adds `@types/simple-oauth2` and uses the types from that one instead – and does so in a backwards compatible way by keeping `ProviderConfiguration` and `Credentials`.

My personal motivation for this was that I wanted to add a HTTP Header to some requests (I want to add a `User-Agent` as I personally think that's good practice to do) and when I looked around if it was supported I realized that it was, but through the `Credentials['http']` that's currently typed as:

```ts
http?: {} | undefined;
```

[This is what it looks like](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/091544cc1a6cc86156761480156cae241e73853e/types/simple-oauth2/index.d.ts#L53-L79) in `@types/simple-oauth2`, much more complete:

```ts
http?: Omit<WreckHttpOptions, 'baseUrl' | 'headers' | 'redirects' | 'json'> & {
    baseUrl?: undefined;
    headers?: {
        /**
         * Acceptable http response content type. Defaults to application/json
         */
        accept?: string;
        /**
         * Always overriden by the library to properly send the required credentials on each scenario
         */
        authorization?: string;
        [key: string]: unknown
    } | undefined;
    /**
     * Number or redirects to follow. Defaults to false (no redirects)
     */
    redirects?: false | number | undefined;
    /**
     * JSON response parsing mode. Defaults to strict
     */
    json?: boolean | "strict" | "force" | undefined;
 } | undefined;
```

When looking through the git log, PR:s and issues I can't find any mentioning of why these types wasn't referred to instead of duplicating them. Maybe the `@types/simple-oauth2` wasn't available at the time, but now that they are I think its a good idea to refer to them.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-08-26 10:04 UTC, Uzlopak requested changes
Lets discuss this first:

By putting it as dependency and not dev dependency the types package will also be installed as production dependencies by Projects that use this plugin.

2023-08-26 10:13 UTC, voxpelli commented
> By putting it as dependency and not dev dependency the types package will also be installed as production dependencies by Projects that use this plugin.

Yes, that is unfortunate, it's a balancing act between smaller install size and correct/complete types I think.

One improvement could be that this module stops blankety passing through the options to `simple-oauth2` and instead manages its own.

Another could be to add these types as a dev dependency and validate in the type tests that the types defined in this module are indeed assignable to the one in `simple-oauth2`

The latter I would then like to complement with fleshing out some of the http options (which in the `simple-oauth2` types extend from `wreck`, so would need to be partially copied from there as well)

2023-08-26 10:18 UTC, Uzlopak commented
Maybe better to talk to the simple-oauth2 team to merge this PR
https://github.com/lelylan/simple-oauth2/pull/436

2023-08-26 10:29 UTC, voxpelli commented
@Uzlopak One doesn't exclude the other. Also, that PR has some of the same concerns (https://github.com/lelylan/simple-oauth2/pull/436#issuecomment-1694252323) as I raise here.

2023-08-26 10:37 UTC, voxpelli commented
I'll make an alternative PR soon that avoids adding this as a prod dependency

2023-08-26 12:39 UTC, voxpelli commented
@Uzlopak Perhaps the solution here is better then? https://github.com/fastify/fastify-oauth2/pull/229

2023-08-27 15:27 UTC, voxpelli commented
Closing in favor of #229

2023-08-27 15:27 UTC, closed without merging